CREATE TABLE [auth].[Groups]
(
	[Id]		INT IDENTITY(1,1)	NOT NULL,
	[Name]		NVARCHAR(150)		NOT NULL,
	[CreatedAt]	DATETIME			NULL,
	[UpdatedAt]	DATETIME			NULL
) ON [PRIMARY]
GO

ALTER TABLE [auth].[Groups]
	ADD CONSTRAINT DF_Groups_UpdatedAt
		DEFAULT GETUTCDATE() FOR [UpdatedAt]
